grails-app/domain/converter/CreateDomainModel.groovy
package converter

class CreateDomainModel {

    static constraints = {
    }
}

grails-app/domain/converter/Grails.groovy
package converter

class Grails {

    static constraints = {
    }
}

grails-app/domain/sec/treasurer/Transacciones.groovy
package sec.treasurer

class Transacciones {
	
	int id
	String descripcion
	String fecha

    static constraints = {
    }
}

grails-app/domain/sec/treasurer/User.groovy
package sec.treasurer

class User {
	String userName
	String password
	String fullName
	String toString(){
		"${fullName}"
	}
    static constraints = {
		fullName()
		userName(unique:true)
		password(password: true)
    }
}

grails-app/domain/sec/treasurer/Valores.groovy
package sec.treasurer

import java.util.Formatter.DateTime;

class Valores {
	int id;
	String moneda;
	String valor;
	String xfecha;

    static constraints = {
    }
}

grails-app/controllers/sec/treasurer/HelloController.groovy
package sec.treasurer

import grails.converters.JSON

class HelloController {

    def world={ 
		
		return 5
	}
}

grails-app/controllers/sec/treasurer/TransaccionesController.groovy
package sec.treasurer

import java.util.regex.Pattern.Script;

class TransaccionesController {

    def scaffold = Transacciones
	
	
}

grails-app/controllers/sec/treasurer/UserController.groovy
package sec.treasurer

class UserController {
	
	

    def index() {
		redirect(action:"login")
	}
	
	def login={}
	def admin={}
	
	def authenticate={
		def user = User.findByUserNameAndPassword(params.userName, params.password)
		
		if(user){
			session.user=user
			flash.message="Hello ${user.fullName}!"
			redirect (action:"login")
		}
		else{
			flash.message="Sorry, ${params.userName}. Please try again."
			redirect(action:"login")
		}
	}
	
	def logout={
		flash.message="Goodbye ${session.user.fullName}"
		session.user=null
		redirect(action:"login")
	}
	
	def regresaDollar(){
		Valores v = Valores.get(3)
		def valor = (v.valor) as String
		render valor as String
	}
	
	def regresaMx(){
		Valores v = Valores.get(1)
		def valor = (v.valor) as String
		render valor as String
	}
	
	def regresaEuro(){
		Valores v = Valores.get(2)
		def valor = (v.valor) as String
		render valor as String
	}
	
	def regresaCan(){
		Valores v = Valores.get(4)
		def valor = (v.valor) as String
		render valor as String
	}
	
	def regresaGBP(){
		Valores v = Valores.get(5)
		def valor = (v.valor) as String
		render valor as String
	}
	
	def regresaYen(){
		Valores v = Valores.get(6)
		def valor = (v.valor) as String
		render valor as String
	}
	
	def registro(){
		Valores mx = Valores.get(1)
		Valores us = Valores.get(3)
		Valores ca = Valores.get(4)
		Valores eu = Valores.get(2)
		Valores gb = Valores.get(5)
		Valores ye = Valores.get(6)
		def valormx = (mx.valor) as String
		def valorus = (us.valor) as String
		def valorca = (ca.valor) as String
		def valoreu = (eu.valor) as String
		def valorgb = (gb.valor) as String
		def valorye = (ye.valor) as String
		
		def descripcion="Valores anteriores; Mexican Pesos: "+valormx+", US Dollars: "+valorus+", Canadian Dollars: "+valorca+", Euro: "+valoreu+", GBP: "+valorgb+", Yen: "+valorye
		
		def fecha = (new Date()) as String
		new Transacciones(descripcion:descripcion, fecha:fecha).save()		
	}
	
	def registro2(){
		Valores mx = Valores.get(1)
		Valores us = Valores.get(3)
		Valores ca = Valores.get(4)
		Valores eu = Valores.get(2)
		Valores gb = Valores.get(5)
		Valores ye = Valores.get(6)
		def valormx = (mx.valor) as String
		def valorus = (us.valor) as String
		def valorca = (ca.valor) as String
		def valoreu = (eu.valor) as String
		def valorgb = (gb.valor) as String
		def valorye = (ye.valor) as String		
		def descripcion="Valores actuales; Mexican Pesos: "+valormx+", US Dollars: "+valorus+", Canadian Dollars: "+valorca+", Euro: "+valoreu+", GBP: "+valorgb+", Yen: "+valorye		
		def fecha = (new Date()) as String
		new Transacciones(descripcion:descripcion, fecha:fecha).save()
	}
	
	def hola(String descripcion){
		def fecha = (new Date()) as String
		new Transacciones(descripcion:descripcion, fecha:fecha).save()		
	}
}
 	

grails-app/controllers/sec/treasurer/ValoresController.groovy
package sec.treasurer

class ValoresController {

    def scaffold = Valores
}

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title><g:layoutTitle default="Grails"/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">
		<link rel="apple-touch-icon" href="${resource(dir: 'images', file: 'apple-touch-icon.png')}">
		<link rel="apple-touch-icon" sizes="114x114" href="${resource(dir: 'images', file: 'apple-touch-icon-retina.png')}">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'main.css')}" type="text/css">
		<link rel="stylesheet" href="${resource(dir: 'css', file: 'mobile.css')}" type="text/css">
		<g:layoutHead/>
		<r:layoutResources />
	</head>
	<body>
		<div id="grailsLogo" role="banner"><a href="http://grails.org"><img src="${resource(dir: 'images', file: 'grails_logo.png')}" alt="Grails"/></a></div>
		<g:layoutBody/>
		<div class="footer" role="contentinfo"></div>
		<div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
		<g:javascript library="application"/>
		<r:layoutResources />
	</body>
</html>

grails-app/views/user/admin.gsp
<%@ page import="sec.treasurer.User"%>
<!doctype html>
<html>
<head>
<g:javascript library="jquery"/>
<meta name="layout" content="main">
<g:set var="entityName" value="ProjectTracker Admin"></g:set>
<title><g:message code="ProjectTracker Admin"
		args="[entityName]" /></title>
</head>
<body>
	<div id="page-body" role="main">
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri:'/')}">Principal</a></li>

			</ul>
		</div>
		<div id="controller-list" class="content scaffold-create" role="main">
			<h1>Administración</h1>
			<br>
			<script type="text/javascript">
				function registra(){
			    	<g:remoteFunction controller="user" action="registro"/>;   
					}
			</script>
			<div id="list" class="navigation">
				<ul>
				
					<li onclick="registra()"><a class="list" href="${createLink(uri:'/valores/')}">Administrar
							tipos de conversión</a></li>
					<br>
					<li><a class="list"
						href="${createLink(uri:'/transacciones/')}">Administrar
							transacciones</a></li>
					<br>
					<li><a class="list"
						href="${createLink(uri:'/transacciones/list/')}">Historial de
							transacciones</a></li>
					<br>
					<li><a class="list" href="${createLink(uri:'/valores/list/')}">Lista
							de valores monetarios</a></li>
					<br>
				</ul>
			</div>
			
		</div>
	</div>
</body>
</html>

grails-app/views/user/login.gsp
<%@ page import="sec.treasurer.User"%>
<!doctype html>
<html>
<head>
<meta name="layout" content="main">
<g:set var="entityName" value="ProjectTracker Login"></g:set>
<title><g:message code="ProjectTracker Login" args="[entityName]"/></title>
</head>
<body>
	<div class="nav" role="navigation">
		<ul>
			<li><a class="home" href="${createLink(uri:'/')}">Home</a></li>
			<li><g:link class="list" action="logout">Logout</g:link></li>
		</ul>
	</div>
	<div id="create-endUser" class="content scaffold-create" role="main">
		<h1>login</h1>
		<g:if test="${flash.message}">
			<div class="message" role="status">
				${flash.message}
			</div>
		</g:if>
		<g:hasErrors bean="${userInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${userInstance}" var="error">
					<li
						<g:if test="${error in org.springframework.validation.FieldError }" > data-field-id="${error.field }"</g:if>><g:message
							error="${error }" /></li>
				</g:eachError>
			</ul>
		</g:hasErrors>
		<g:form action="authenticate">
			<fieldset class="form">
				<div
					class="fieldcontain ${hasErrors(bean:userInstance, field: 'userName','error') }">
					<label for="userName"> <g:message
							code="endUser.userName.label" default="userName" />
					</label>
					<g:textField name="userName" value="${userInstance?.userName}" />
				</div>
				<div
					class="fieldcontain ${hasErrors(bean:userInstance, field: 'password', 'error') }">
					<label for="password"> <g:message
							code="endUser.password.label" default="password" />
					</label>
					<g:field type="password" name="password" value="${userInstance?.password}" />
				</div>
			</fieldset>
			<fieldset class="buttons">
				<g:submitButton name="login" class="save" value="Login"/>
			</fieldset>
		</g:form>
	</div>
</body>
</html>